### ISSUE TITLE
not able to set bold font weight

### ISSUE THREAD

**Issue by kyugoa** [Pietervdw/questpdf-sizetest#2]
hi Thanks for the demo, but it looks like when registering the subset, there is not bold font included. is there a way to register the bold font set as well?

**Comment by Pietervdw** [comment]
Hi @kyugoa 

It should be possible to follow the same process of creating a subset of the bold version for your font of choice and then reference the bold font name where required.

**Comment by kyugoa** [comment]
yea I think it was the issue with the font pack I used. I registered the bold font pack now the bold fonts show up. thx
